version: '3'

services:
  chat2api:
    image: lanqian528/chat2api:latest
    container_name: chat2api
    restart: unless-stopped
    ports:
      - '5005:5005'
    volumes:
      - ./data:/app/data # 挂载一些需要保存的数据
    environment:
      - TZ=Asia/Shanghai # 设置时区
      - ARKOSE_TOKEN_URL=http://arkose:5006/token # 已内置，不要改动
      - AUTHORIZATION=sk-this-is-a-chat2api-free-key
      - CHATGPT_BASE_URL=https://chatgpt.com
      - HISTORY_DISABLED=true
      - POW_DIFFICULTY=000032
      - RETRY_TIMES=3
      - ENABLE_GATEWAY=true
      - CONVERSATION_ONLY=false
      - ENABLE_LIMIT=true
      - UPLOAD_BY_URL=false

  arkose:
    image: lanqian528/funcaptcha_solver:latest
    container_name: funcaptcha_solver
    restart: unless-stopped
    ports:
      - '5006:5006'
    environment:
      - TZ=Asia/Shanghai # 设置时区
